/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controller.MainController;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import misc.Constants;
import misc.PropertyFile;

/**
 *
 * @author GioXsanX
 */
public class VistaPrincipal extends javax.swing.JFrame {
MainController mc;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
initComponents();
set();
applySettings();
    }
public void set(){
    mc=new MainController(this);
      this.compraItem.addActionListener(mc);
   this.cajaItem.addActionListener(mc);
  this.setItem.addActionListener(mc);
  this.salirItem.addActionListener(mc);

}
public void showChild(JInternalFrame frame,boolean maximizeFrame){
        desktop.add(frame);
        frame.setVisible(true);
        if(maximizeFrame){
            desktop.getDesktopManager().maximizeFrame(frame);            
        }
    }
public void applySettings(){
        //Instancia de la clase PropertyFile
        PropertyFile pf = new PropertyFile();
        pf.open();
        if(pf.isFileExists()){
            this.companyNameLabel.setText(pf.getProperty(Constants.COMPANYNAME_PROPERTY));
        }
        else{
            if(JOptionPane.showConfirmDialog(this, "Aún no se ha realizado la configuración inicial. ¿Deseas hacerla ahora?", "Configurar",
                    JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE)==JOptionPane.YES_OPTION){
                mc.showSettingsDialog();
                pf.open();
                this.companyNameLabel.setText(pf.getProperty(Constants.COMPANYNAME_PROPERTY));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        companyNameLabel = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        compraItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        cajaItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        setItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salirItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(companyNameLabel);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other Sources/images/shop.png"))); // NOI18N
        jMenu1.setText("Registrar");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        compraItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other Sources/images/iconfinder_103222_warehouse_icon_16px.png"))); // NOI18N
        compraItem.setText("Existencia ");
        compraItem.setActionCommand("existencia");
        jMenu1.add(compraItem);
        jMenu1.add(jSeparator2);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other Sources/images/iconfinder_6358091_basket_buy_cart_ecommerce_online_icon_16px.png"))); // NOI18N
        jMenuItem2.setText("Ventas");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator3);

        cajaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other Sources/images/iconfinder_134157_money_cashier_dollar_currency_icon_16px.png"))); // NOI18N
        cajaItem.setText("Caja");
        jMenu1.add(cajaItem);
        jMenu1.add(jSeparator4);

        setItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other Sources/images/set.png"))); // NOI18N
        setItem.setText("Configuraciones");
        setItem.setActionCommand("configuracion");
        jMenu1.add(setItem);
        jMenu1.add(jSeparator1);

        salirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Other Sources/images/exit.png"))); // NOI18N
        salirItem.setText("Exit");
        salirItem.setActionCommand("salir");
        jMenu1.add(salirItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Inventario");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jMenuItem4.setText("Mostrar");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cajaItem;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JMenuItem compraItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem salirItem;
    private javax.swing.JMenuItem setItem;
    // End of variables declaration//GEN-END:variables
}
